#' Run the MCMC on a BBT model
#'
#' @inheritParams bbtcomp
#' @param tablex A wintable
#' @param use_davidson Whether to use the Davidson model to deal with ties
#' @param simplified Whether to use the simplified model. If hyper_prior, or
#'     scale are set, or davidson is set to TRUE, then simplified should be FALSE
#' @param ... Further parameters to the MCMC (cmdstanr model and fit)
#'
#' @return A fitted BBT model
#' @export
#'
#' @examples
#' \donttest{
#' ss <- ll[1:80, 1:6] # first 20 datasets and 5 algorithms
#'
#' wintable <- make_wintable(ss, lrope = FALSE)
#'
#' m1 <- mcmcbbt(wintable, TRUE, hyper_prior = 0, scale = 0.5,
#'      use_davidson = TRUE, use_log_lik = FALSE)
#'
#' m2 <- mcmcbbt(wintable, TRUE, iter_sampling = 2000, seed = 1234)
#' }
mcmcbbt <- function(tablex,
                    simplified = TRUE,
                    hyper_prior = 0,
                    scale = 0.5,
                    use_davidson = FALSE,
                    use_log_lik = FALSE,
                    dir = NULL,
                    ...) {

  pairs <- tablex$table
  N <- nrow(pairs)
  K <- length(tablex$alg_names)
  data <- list(K = K,
               N = N,
               player1 = as.integer(pairs$pi),
               player2 = as.integer(pairs$pj),
               win1 = pairs$win1,
               win2 = pairs$win2)

  #Directory for csv files
  outdir <- dir
  if (is.null(dir)) {
    outdir <- file.path(getwd(),'.bbtcomp')
    dir.create(outdir, showWarnings = FALSE)
  } else{
    dir.create(dir, showWarnings = FALSE)
  }


  if (simplified) {
    model_file <-
      system.file("stan",
                  "bbt-simplified.stan",
                  package = "bbtcomp",
                  mustWork = TRUE)
  } else {
    data <- c(data,
              list(use_davidson = as.integer(use_davidson),
                   use_log_lik = as.integer(use_log_lik),
                   hyp = hyper_prior,
                   scale = scale,
                   ties = pairs$ties))
    model_file <-
      system.file("stan",
                  "bbt-full.stan",
                  package = "bbtcomp",
                  mustWork = TRUE)
  }

  model <- cmdstanr::cmdstan_model(model_file, dir = outdir)
  fit <- model$sample(data = data,
                      refresh = 0,
                      output_dir = outdir, ...)

  ## need this to read the .csv files generated by cmdstand$sample
  diagnostics <- fit$sampler_diagnostics()
  draws <- fit$draws()
  return(list(model = fit,
              davidson = use_davidson,
              log_lik = use_log_lik,
              wintable = tablex))
}
