#' Run the MCMC on a BBT model
#'
#' @inheritParams bbtcomp
#' @param tablex A wintable
#' @param use_davidson Whether to use the Davidson model to deal with ties
#' @param ... Further parameters to the MCMC (cmdstanr model and fit)
#'
#' @return A fitted BBT model
#' @export
#'
#' @examples
#' \donttest{
#' ss <- ll[1:80, 1:6] # first 20 datasets and 5 algorithms
#'
#' wintable <- make_wintable(ss, lrope = FALSE)
#'
#' options(mc.cores = parallel::detectCores(logical = FALSE))
#'
#' m1 <- mcmcbbt(wintable, hyper_prior = 0, scale = 0.5,
#'      use_davidson = TRUE)
#'
#' m2 <- mcmcbbt(wintable, iter_sampling = 2000, seed = 1234)
#' }
mcmcbbt <- function(tablex,
                    hyper_prior = 0,
                    scale = 0.5,
                    use_davidson = FALSE,
                    ...) {

  pairs <- tablex$table
  N <- nrow(pairs)
  K <- length(tablex$alg_names)
  data <- list(K = K,
               N = N,
               player1 = as.integer(pairs$pi),
               player2 = as.integer(pairs$pj),
               win1 = pairs$win1,
               win2 = pairs$win2)

  #Directory for stan compiled file and csv files
  outdir <- getOption("bbtcomp.dir",default = tempdir())
  dir.create(outdir, showWarnings = FALSE)


  data <- c(data,
            list(use_davidson = as.integer(use_davidson),
                   hyp = hyper_prior,
                   scale = scale,
                   ties = pairs$ties))
  model_file <-
      system.file("stan",
                  "bbt-full.stan",
                  package = "bbtcomp",
                  mustWork = TRUE)


  model <- cmdstanr::cmdstan_model(model_file, dir = outdir)
  fit <- model$sample(data = data,
                      refresh = 0,
                      output_dir = outdir,
                      ...)

  ## need this to read the .csv files generated by cmdstand$sample
  diagnostics <- fit$sampler_diagnostics()
  draws <- fit$draws()


  return(list(model = fit,
              davidson = as.logical(use_davidson),
              wintable = tablex))
}
